---
title: "RiverPlot"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(riverplot)
library(RColorBrewer)
library(ggplot2)
```

#Example
```{r}
x <- riverplot.example()
x
plot(x)
```

```{r}
nodes <- data.frame(ID = c(LETTERS[1:16]),
                    labels = c( A= "店外", B= "櫥窗", C= "離開", D="進店",
                      E="離開", F="有效", G="試穿", H="離開", I="購買",J="離開",K="離開",
                      L="系列1", M="系列2", N="系列3", O="系列4", P="系列5"),
                    x = c(1,2,3,3,4,4,5,6,6,6,3,7,7,7,7,7),
                    y = c(4,7,0,3,1,4,7,2,5,9,8,3,4,5,6,7),
                    col = c("#80B1D3","#80B1D3","#FFFFB3","#80B1D3","#FFFFB3",
                            "#80B1D3","#80B1D3","#FFFFB3","#80B1D3","#FFFFB3","#FFFFB3",
                            "#FFFFB3","#FFFFB3","#FFFFB3","#FFFFB3","#FFFFB3"),
                    stringsAsFactors = FALSE
)
edges <- data.frame( N1= c("A","A","A","B","B","D","D","F","F","F","G","G","I","I","I","I","I"), 
                     N2= c("B","C","D","K","D","E","F","G","H","I","I","J","L","M","N","O","P"), 
                     Value = c(0.2,0.7,0.1,0.6,0.4,0.5,0.5,0.2,0.7,0.1,
                               0.3,0.7,0.1,0.3,0.2,0.1,0.3))
r <- makeRiver(nodes,edges)
plt<-riverplot(r,default_style = list(srt=0),
          node_margin = 0.2, nodewidth = 3, plot_area = 1)

X<-NULL
Y<-NULL
for(i in 1:nrow(edges)){
  n1 = as.character(edges[i,"N1"])
  n2 = as.character(edges[i,"N2"])
  x_coord = (plt[,n1]["x"]+plt[,n2]["x"])/2
  y_coord = (plt[,n1]["center"]+plt[,n2]["center"])/2
  X<-append(X,x_coord)
  Y<-append(Y,y_coord)
}
X<-unname(X)
Y<-unname(Y)
percentage<-paste0(edges$Value*100,"%")
text(X,Y,as.character(percentage),cex=0.8)
```


```{r}
nodes <- data.frame(ID = c(LETTERS[1:18]),
                    labels = c( A= "店外", B= "離開", C="進店",
                      D="離開", E="互動", F="離開", G="購買",
                      H="其他", I="系列4", J="系列3", K="系列2",L="系列1",
                      M="其他", N="系列4", O="系列3", P="系列2",Q="系列1",R="潛在"),
                    x = c(1,7,6,12,10,22,21,14,14,14,14,14,24,24,24,24,24,18),
                    y = c(4,0,3,0,4,2,6,2.8,3.4,4,4.6,5.2,4.8,5.4,6,6.6,7.2,4),
                    col =
                      c("#80B1D3","#FFFFB3","#80B1D3","#FFFFB3","#80B1D3","#FFFFB3","#80B1D3",
                            "#BEBADA","#BEBADA","#BEBADA","#BEBADA","#BEBADA",
                            "#BEBADA","#BEBADA","#BEBADA","#BEBADA","#BEBADA","#80B1D3"),
                    stringsAsFactors = FALSE
)
edges <- data.frame( N1= c("A","A","C","C","E","E","E","E","E",
                           "H","I","J","K","L","R","R","G","G","G","G","G"), 
                     N2= c("B","C","D","E","H","I","J","K","L",
                           "R","R","R","R","R","F","G","M","N","O","P","Q"), 
                     Value = c(0.9,0.1,0.5,0.5,
                               0.2,0.4,0.2,0.1,0.1,
                               0.2,0.4,0.3,0.2,0.1,0.7,0.3,
                               0.2,0.2,0.1,0.2,0.3))
r <- makeRiver(nodes,edges)
plt<-riverplot(r,default_style = list(srt=0,textcex=0.7),
          node_margin = 0.3, nodewidth = 3, plot_area = 1.1)

X<-NULL
Y<-NULL
for(i in 1:nrow(edges)){
  if(i%in%c(1:4,15,16)){
    n1 = as.character(edges[i,"N1"])
    n2 = as.character(edges[i,"N2"])
    x_coord = (plt[,n1]["x"]+plt[,n2]["x"])/2
    y_coord = (plt[,n1]["center"]+plt[,n2]["center"])/2
    X<-append(X,x_coord)
    Y<-append(Y,y_coord)
  }
  else{
    n = ifelse(i<10|i>14,as.character(edges[i,"N2"]),as.character(edges[i,"N1"]))
    n2 = ifelse(i<10|i>14,as.character(edges[i+1,"N2"]),as.character(edges[i+1,"N1"]))
    x_coord = plt[,n]["x"]
    y_coord = ifelse(i%in%c(9,14,21),plt[,n]["top"]+0.035,
                     (plt[,n]["center"]+plt[,n2]["center"])/2)
    X<-append(X,x_coord)
    Y<-append(Y,y_coord)
  }
}
X<-unname(X)
Y<-unname(Y)
X<-X[-c(5:9)]
Y<-Y[-c(5:9)]
percentage<-paste0(edges$Value[-c(5:9)]*100,"%")
text(X,Y,as.character(percentage),cex=0.7)
```

```{r}
nodes <- data.frame(ID = c(LETTERS[1:22]),
                    labels = c( A= "店外", B= "離開", C="進店",
                      D="離開", E="互動", F="離開", G="購買",
                      H="系列1", I="系列2", J="系列3", K="系列4", L="系列5",M="系列6",N="系列7",
                      O="系列1", P="系列2", Q="系列3", R="系列4", S="系列5",T="系列6",U="系列7",
                      V="潛在"),
                    x = c(1,4,4,8,6,16,15,9.0,9.0,9.0,9.0,9.0,9.0,9.0,18,18,18,18,18,18,18,12),
                    y = c(4,0,3,0,4,2 ,6 ,2.2,2.8,3.4,4.0,4.6,5.2,5.8,4.2,4.8,5.4,6,6.6,7.2,7.8,4),
                    col =
                      c("#80B1D3","#FFFFB3","#80B1D3","#FFFFB3","#80B1D3","#FFFFB3","#80B1D3",
                        "#FFFFB3","#FFFFB3","#FFFFB3","#FFFFB3","#FFFFB3","#FFFFB3","#FFFFB3",
                        "#FFFFB3","#FFFFB3","#FFFFB3","#FFFFB3","#FFFFB3","#FFFFB3","#FFFFB3",
                        "#80B1D3"),
                    stringsAsFactors = FALSE
)
edges <- data.frame( N1= c("A","A","C","C","E","E","E","E","E","E","E",
                           "H","I","J","K","L","M","N","V","V","G","G","G","G","G","G","G"), 
                     N2= c("B","C","D","E","H","I","J","K","L","M","N",
                           "V","V","V","V","V","V","V","F","G","O","P","Q","R","S","T","U"), 
                     Value = c(0.9,0.1,0.5,0.5,
                               0.05,0.2,0.15,0.2,0.3,0.05,0.05,
                               0.05,0.2,0.15,0.2,0.3,0.05,0.05,0.7,0.3,
                               0.1,0.2,0.05,0.15,0.1,0.05,0.35))
r <- makeRiver(nodes,edges)
plt<-riverplot(r,default_style = list(srt=0,textcex=0.7),
          node_margin = 0.2, nodewidth = 3, plot_area = 1.2)

X<-NULL
Y<-NULL
for(i in 1:nrow(edges)){
  n1 = as.character(edges[i,"N1"])
  n2 = as.character(edges[i,"N2"])
  x_coord = (plt[,n1]["x"]+plt[,n2]["x"])/2
  y_coord = (plt[,n1]["center"]+plt[,n2]["center"])/2
  X<-append(X,x_coord)
  Y<-append(Y,y_coord)
}
X<-unname(X)
Y<-unname(Y)
percentage<-paste0(edges$Value*100,"%")
text(X,Y,as.character(percentage),cex=0.8)
```



